"""Render the locked Dice count-posterior analysis as a table and forest plot."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from scripts.analyze.counts import METHODS
from selectseg.artifacts import sha256_file


DATASETS = (
    ("pet", "Oxford Pet"),
    ("kvasir", "Kvasir-SEG"),
    ("fives", "FIVES"),
    ("isic", "ISIC 2018"),
    ("tn3k", "TN3K"),
)
MODELS = (
    ("clipseg-target", "CLIPSeg target (CLIP-T)"),
    ("deeplabv3-target", "DeepLabV3 target (DL-T)"),
)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--analysis", required=True)
    parser.add_argument("--output-dir", required=True)
    return parser.parse_args(argv)


def _load(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if value.get("analysis_id") != "dice-count-result-analysis-v1":
        raise ValueError("unexpected Dice count analysis")
    conditions = value.get("conditions")
    if not isinstance(conditions, list) or len(conditions) != 10:
        raise ValueError("Dice count rendering requires ten conditions")
    observed = {(row["dataset"], row["condition"]) for row in conditions}
    expected = {(dataset, model) for dataset, _ in DATASETS for model, _ in MODELS}
    if observed != expected:
        raise ValueError("Dice count analysis has an unexpected condition set")
    return value


def _format(value: float, best: bool) -> str:
    rendered = f"{100 * value:.3f}"
    return rf"\bestresult{{{rendered}}}" if best else rendered


def _table(analysis: dict, analysis_sha256: str) -> str:
    lookup = {(row["dataset"], row["condition"]): row for row in analysis["conditions"]}
    lines = [
        "% AUTO-GENERATED by scripts/render/counts.py; DO NOT EDIT.",
        f"% Source analysis SHA-256: {analysis_sha256}",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Dice count-posterior mechanism experiment. Methods are rows and datasets are columns; CLIP-T and DL-T use identical methods. Entries are Dice-risk AURC $\times100$ (lower is better), and dark blue marks the exactly lowest unrounded value in each column. The deployed mask and pixel marginals are fixed; Dice two-block changes only the threshold coupling inside versus outside the action.}",
        r"\label{tab:dice-count-posterior}",
        r"{\scriptsize\setlength{\tabcolsep}{3pt}%",
    ]
    for model, model_label in MODELS:
        lines.extend(
            [
                r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l*{5}{c}@{}}",
                r"\toprule",
                rf"\multicolumn{{6}}{{l}}{{\textit{{{model_label}}}}} \\",
                r"\midrule",
                "Confidence method & " + " & ".join(label for _, label in DATASETS) + r" \\",
                r"\midrule",
            ]
        )
        values = {
            field: [
                lookup[(dataset, model)]["methods"][field]["aurc"]
                for dataset, _ in DATASETS
            ]
            for field, _ in METHODS
        }
        minima = [min(values[field][index] for field, _ in METHODS) for index in range(5)]
        for field, label in METHODS:
            cells = [
                _format(value, value == minima[index])
                for index, value in enumerate(values[field])
            ]
            lines.append(label + " & " + " & ".join(cells) + r" \\")
        lines.extend([r"\bottomrule", r"\end{tabular*}", r"\par\smallskip"])
    lines.extend([r"}", r"\end{table*}", ""])
    return "\n".join(lines)


def _forest(analysis: dict, output: Path) -> None:
    conditions = sorted(
        analysis["conditions"],
        key=lambda row: (
            [dataset for dataset, _ in DATASETS].index(row["dataset"]),
            [model for model, _ in MODELS].index(row["condition"]),
        ),
    )
    differences = np.asarray(
        [row["primary_comparison"]["difference_left_minus_right"] for row in conditions]
    ) * 100
    low = np.asarray(
        [row["primary_comparison"]["bootstrap"]["ci_low"] for row in conditions]
    ) * 100
    high = np.asarray(
        [row["primary_comparison"]["bootstrap"]["ci_high"] for row in conditions]
    ) * 100
    labels = [
        f"{dict(DATASETS)[row['dataset']]} / "
        + ("CLIP-T" if row["condition"] == "clipseg-target" else "DL-T")
        for row in conditions
    ]
    y = np.arange(len(conditions))[::-1]
    figure, axis = plt.subplots(figsize=(6.8, 4.4))
    axis.axvline(0, color="0.45", linewidth=1, linestyle="--")
    colors = np.where(differences < 0, "#004c99", "#a33a2b")
    for position, center, lower, upper, color in zip(
        y, differences, low, high, colors, strict=True
    ):
        axis.errorbar(
            center,
            position,
            xerr=[[center - lower], [upper - center]],
            fmt="o",
            color=color,
            capsize=2,
            markersize=4,
            linewidth=1.1,
        )
    axis.set_yticks(y, labels)
    axis.set_xlabel("Dice AURC difference ×100 (two-block − LevelSet-Q)")
    axis.set_title("Negative values favor the Dice count posterior")
    axis.grid(axis="x", color="0.9", linewidth=0.7)
    figure.tight_layout()
    figure.savefig(output, bbox_inches="tight", metadata={"Creator": __name__})
    plt.close(figure)


def main(argv=None):
    args = parse_args(argv)
    analysis_path = Path(args.analysis)
    analysis = _load(analysis_path)
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)
    table_path = output / "dice_count_posterior.tex"
    figure_path = output / "dice_count_posterior_forest.pdf"
    manifest_path = output / "dice_count_posterior_render.manifest.json"
    if any(path.exists() or path.is_symlink() for path in (table_path, figure_path, manifest_path)):
        raise FileExistsError("Dice count render output already exists")
    analysis_sha256 = sha256_file(analysis_path)
    table_path.write_text(_table(analysis, analysis_sha256), encoding="utf-8")
    _forest(analysis, figure_path)
    manifest = {
        "schema_version": 1,
        "analysis_sha256": analysis_sha256,
        "table_sha256": sha256_file(table_path),
        "figure_sha256": sha256_file(figure_path),
        "source_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"saved {table_path}")
    print(f"saved {figure_path}")


if __name__ == "__main__":
    main()
