"""Render the frozen Ensemble-Q mechanism analysis."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from selectseg.artifacts import sha256_file


DATASETS = (
    ("pet", "Oxford Pet"),
    ("kvasir", "Kvasir-SEG"),
    ("fives", "FIVES"),
    ("isic", "ISIC 2018"),
    ("tn3k", "TN3K"),
)
MODELS = (
    ("clipseg-target", "CLIPSeg target (CLIP-T)"),
    ("deeplabv3-target", "DeepLabV3 target (DL-T)"),
)
PANELS = (
    ("risk_dice", "Dice risk", "confidence_dice_m32", "confidence_ensemble_q_dice"),
    ("risk_nhd", "HD risk", "confidence_nhd_m32", "confidence_ensemble_q_nhd"),
    (
        "risk_nhd95",
        "HD95 risk",
        "confidence_nhd95_m32",
        "confidence_ensemble_q_nhd95",
    ),
)
COMMON_METHODS = (
    ("confidence_sdc", "SDC"),
    ("confidence_negative_entropy", "Negative entropy"),
    ("confidence_threshold_iou_stability", "Threshold-IoU stability"),
    ("confidence_ensemble_negative_mutual_information", "Negative mutual information"),
    ("confidence_ensemble_negative_probability_variance", "Negative probability variance"),
)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--analysis", required=True)
    parser.add_argument("--output-dir", required=True)
    return parser.parse_args(argv)


def _load(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if value.get("analysis_id") != "ensemble-posterior-mechanism-v1":
        raise ValueError("unexpected Ensemble-Q analysis")
    conditions = value.get("conditions")
    if not isinstance(conditions, list) or len(conditions) != 10:
        raise ValueError("Ensemble-Q rendering requires ten conditions")
    observed = {(row["dataset"], row["condition"]) for row in conditions}
    expected = {(dataset, model) for dataset, _ in DATASETS for model, _ in MODELS}
    if observed != expected:
        raise ValueError("Ensemble-Q analysis has an unexpected condition set")
    return value


def _format(value: float, best: bool) -> str:
    rendered = f"{100 * value:.3f}"
    return rf"\bestresult{{{rendered}}}" if best else rendered


def _table(analysis: dict, analysis_sha256: str) -> str:
    lookup = {(row["dataset"], row["condition"]): row for row in analysis["conditions"]}
    lines = [
        "% AUTO-GENERATED by scripts/render/ensemble.py; DO NOT EDIT.",
        f"% Source analysis SHA-256: {analysis_sha256}",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Fixed-action three-checkpoint posterior experiment. Methods are rows and datasets are columns. Entries are raw AURC $\times100$ (lower is better); dark blue marks the exactly lowest unrounded value among the displayed methods in each risk block. LevelSet-Q uses the mean probability map, whereas Ensemble-Q and ensemble uncertainty baselines use the same three member predictions.}",
        r"\label{tab:ensemble-posterior}",
        r"{\scriptsize\setlength{\tabcolsep}{3pt}%",
    ]
    for model, model_label in MODELS:
        lines.extend(
            [
                r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l*{5}{c}@{}}",
                r"\toprule",
                rf"\multicolumn{{6}}{{l}}{{\textit{{{model_label}}}}} \\",
                r"\midrule",
                "Confidence method & " + " & ".join(label for _, label in DATASETS) + r" \\",
            ]
        )
        for risk, risk_label, level_field, ensemble_field in PANELS:
            lines.append(rf"\midrule\multicolumn{{6}}{{l}}{{\emph{{{risk_label}}}}} \\")
            methods = (
                (level_field, "LevelSet-Q (matched)"),
                (ensemble_field, "Ensemble-Q (matched)"),
                *COMMON_METHODS,
            )
            values = {
                field: [
                    lookup[(dataset, model)]["risks"][risk]["methods"][field]["aurc"]
                    for dataset, _ in DATASETS
                ]
                for field, _ in methods
            }
            minima = [min(values[field][index] for field, _ in methods) for index in range(5)]
            for field, label in methods:
                cells = [
                    _format(value, value == minima[index])
                    for index, value in enumerate(values[field])
                ]
                lines.append(label + " & " + " & ".join(cells) + r" \\")
        lines.extend([r"\bottomrule", r"\end{tabular*}", r"\par\smallskip"])
    lines.extend([r"}", r"\end{table*}", ""])
    return "\n".join(lines)


def _forest(analysis: dict, output: Path) -> None:
    order = {(dataset, model): 2 * index + offset for index, (dataset, _) in enumerate(DATASETS) for offset, (model, _) in enumerate(MODELS)}
    conditions = sorted(analysis["conditions"], key=lambda row: order[(row["dataset"], row["condition"])])
    labels = [
        f"{dict(DATASETS)[row['dataset']]} / "
        + ("CLIP-T" if row["condition"] == "clipseg-target" else "DL-T")
        for row in conditions
    ]
    figure, axes = plt.subplots(1, 3, figsize=(12.0, 4.6), sharey=True)
    y = np.arange(len(conditions))[::-1]
    for axis, (risk, title, _, _) in zip(axes, PANELS, strict=True):
        comparison = [row["primary_comparisons"][risk] for row in conditions]
        center = np.asarray([row["difference_left_minus_right"] for row in comparison]) * 100
        low = np.asarray([row["bootstrap"]["ci_low"] for row in comparison]) * 100
        high = np.asarray([row["bootstrap"]["ci_high"] for row in comparison]) * 100
        axis.axvline(0, color="0.45", linewidth=1, linestyle="--")
        colors = np.where(center < 0, "#004c99", "#a33a2b")
        for position, estimate, lower, upper, color in zip(y, center, low, high, colors, strict=True):
            axis.errorbar(
                estimate,
                position,
                xerr=[[estimate - lower], [upper - estimate]],
                fmt="o",
                color=color,
                capsize=2,
                markersize=4,
                linewidth=1.1,
            )
        axis.set_title(title)
        axis.set_xlabel("AURC difference ×100\n(Ensemble-Q − LevelSet-Q)")
        axis.grid(axis="x", color="0.9", linewidth=0.7)
    axes[0].set_yticks(y, labels)
    figure.suptitle("Negative values favor Ensemble-Q", y=1.01)
    figure.tight_layout()
    figure.savefig(output, bbox_inches="tight", metadata={"Creator": __name__})
    plt.close(figure)


def main(argv=None):
    args = parse_args(argv)
    analysis_path = Path(args.analysis)
    analysis = _load(analysis_path)
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)
    table_path = output / "ensemble_posterior.tex"
    figure_path = output / "ensemble_posterior_forest.pdf"
    manifest_path = output / "ensemble_posterior_render.manifest.json"
    if any(path.exists() or path.is_symlink() for path in (table_path, figure_path, manifest_path)):
        raise FileExistsError("Ensemble-Q render output already exists")
    analysis_sha256 = sha256_file(analysis_path)
    table_path.write_text(_table(analysis, analysis_sha256), encoding="utf-8")
    _forest(analysis, figure_path)
    manifest = {
        "schema_version": 1,
        "analysis_sha256": analysis_sha256,
        "table_sha256": sha256_file(table_path),
        "figure_sha256": sha256_file(figure_path),
        "source_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"saved {table_path}")
    print(f"saved {figure_path}")


if __name__ == "__main__":
    main()
