"""Render the fixed Gate-C reversal summary as a compact LaTeX table.

The source analysis stores raw AURC units.  This renderer displays the
predeclared nHD-minus-nHD95 contrast under nHD95 risk after multiplication by
100, without changing the machine-readable analysis.  It is intentionally a
small main-text companion to the complete three-seed appendix table.
"""

from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path

from scripts.analyze.seed import validate_analysis_document
from selectseg.seed.extension import _load_json, _sha256


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "Tables" / "seed_sensitivity_main.tex"
CONTRAST = "nhd_vs_nhd95_under_nhd95"
DATASETS = ("pet", "kvasir", "fives", "isic", "tn3k")
DATASET_LABELS = {
    "pet": "Oxford Pet",
    "kvasir": "Kvasir-SEG",
    "fives": "FIVES",
    "isic": "ISIC",
    "tn3k": "TN3K",
}
CONDITIONS = ("clipseg-target", "deeplabv3-target")
CONDITION_LABELS = {
    "clipseg-target": "CLIP-T",
    "deeplabv3-target": "DL-T",
}
EXPECTED_REVERSAL_CELLS = frozenset(
    {
        ("clipseg-target", "isic"),
        ("clipseg-target", "tn3k"),
        ("deeplabv3-target", "kvasir"),
        ("deeplabv3-target", "isic"),
        ("deeplabv3-target", "pet"),
    }
)
EXPECTED_DAGGER_CELLS = frozenset(
    {
        ("clipseg-target", "tn3k"),
        ("deeplabv3-target", "isic"),
        ("deeplabv3-target", "pet"),
    }
)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--analysis", required=True)
    parser.add_argument("--expected-analysis-sha256", required=True)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    return parser.parse_args(argv)


def _strict_digest(value, *, location):
    if (
        not isinstance(value, str)
        or len(value) != 64
        or any(character not in "0123456789abcdef" for character in value.lower())
    ):
        raise ValueError(f"{location} must be a SHA-256 hex digest")
    return value.lower()


def load_analysis(path, *, expected_sha256):
    source = Path(path)
    if not source.is_file() or source.is_symlink():
        raise FileNotFoundError(
            f"seed analysis must be a regular non-symlink file: {source}"
        )
    expected = _strict_digest(
        expected_sha256, location="expected seed analysis SHA-256"
    )
    observed = _sha256(source)
    if observed != expected:
        raise ValueError("seed analysis SHA-256 mismatch")
    analysis = _load_json(source)
    by_key = validate_analysis_document(analysis)
    return analysis, by_key, observed


def _gate_cells(analysis, by_key):
    reversal_cells = set()
    dagger_cells = set()
    for condition in CONDITIONS:
        for dataset in DATASETS:
            summary = by_key[(dataset, condition)]["summary"]["contrasts"][CONTRAST]
            if summary["direction_reversal"]:
                reversal_cells.add((condition, dataset))
                if not summary["seed0_is_majority_direction"]:
                    dagger_cells.add((condition, dataset))

    gate = analysis["gate_c"]
    listed_nonmajority = {
        (entry["condition"], entry["dataset"], entry["contrast"])
        for entry in gate["seed0_not_majority_cells"]
    }
    expected_nonmajority = {
        (condition, dataset, CONTRAST)
        for condition, dataset in EXPECTED_DAGGER_CELLS
    }
    if not gate["fired"]:
        raise ValueError("Gate C did not fire")
    if gate["direction_reversal_counts"].get(CONTRAST) != 5:
        raise ValueError("Gate C does not report exactly five target reversals")
    if gate["contrasts_with_at_least_three_reversals"] != [CONTRAST]:
        raise ValueError("target contrast did not reach the Gate-C reversal threshold")
    if reversal_cells != EXPECTED_REVERSAL_CELLS:
        raise ValueError("target reversal cells differ from the fixed Gate-C result")
    if dagger_cells != EXPECTED_DAGGER_CELLS:
        raise ValueError("seed-0 non-majority cells differ from the fixed Gate-C result")
    if listed_nonmajority != expected_nonmajority:
        raise ValueError("Gate-C non-majority ledger differs from the target summaries")
    return reversal_cells, dagger_cells


def _contrast_cell(summary, *, dagger):
    values = summary["values"]
    displayed = "/".join(
        f"{100 * float(values[str(seed)]):+.3f}" for seed in (0, 1, 2)
    )
    marker = r"^{\dagger}" if dagger else ""
    return rf"$\bigl({displayed}\bigr){marker}$"


def render_table(analysis, by_key, *, analysis_sha256):
    reversal_cells, dagger_cells = _gate_cells(analysis, by_key)
    lines = [
        "% AUTO-GENERATED by scripts/render_seed_gate_table.py; DO NOT EDIT.",
        f"% Source seed analysis SHA-256: {analysis_sha256}",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Checkpoint-level direction reversals for nHD versus nHD95 under "
        r"nHD95 risk. Each populated cell reports "
        r"$100\!\times\![\operatorname{AURC}(C_{\mathrm{nHD}})-"
        r"\operatorname{AURC}(C_{\mathrm{nHD95}})]$ for seeds 0/1/2; negative "
        r"values favor nHD. Only the five cells that reverse direction are shown; "
        r"all other cells are dashes. $\dagger$ marks the three cells for which "
        r"seed 0 disagrees with the majority direction. These are descriptive "
        r"results from three independently trained checkpoints, not seed-level "
        r"inference.}",
        r"\label{tab:seed-sensitivity-main}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        "Model & "
        + " & ".join(DATASET_LABELS[dataset] for dataset in DATASETS)
        + r" \\",
        r"\midrule",
    ]
    for condition in CONDITIONS:
        cells = []
        for dataset in DATASETS:
            key = (condition, dataset)
            if key not in reversal_cells:
                cells.append(r"--")
                continue
            summary = by_key[(dataset, condition)]["summary"]["contrasts"][CONTRAST]
            cells.append(_contrast_cell(summary, dagger=key in dagger_cells))
        lines.append(
            " & ".join([CONDITION_LABELS[condition], *cells]) + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def _write_text_new(path, payload):
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.link(temporary, destination)
        except FileExistsError as error:
            raise FileExistsError(f"refusing to overwrite {destination}") from error
    finally:
        temporary.unlink(missing_ok=True)


def main(argv=None):
    args = parse_args(argv)
    analysis, by_key, digest = load_analysis(
        args.analysis, expected_sha256=args.expected_analysis_sha256
    )
    output = Path(args.output)
    payload = render_table(analysis, by_key, analysis_sha256=digest)
    _write_text_new(output, payload)
    print(f"saved {output}")
    print(f"table_sha256={_sha256(output)}")
    return output


if __name__ == "__main__":
    main()
