"""Render the locked three-seed robustness summary as a compact LaTeX table.

The analysis stores raw AURC units.  Consistent with the manuscript, this
renderer displays signed AURC contrasts multiplied by 100 and leaves all
underlying JSON values unchanged.  It reports both the three checkpoint-level
values and their predeclared mean, range, and sample standard deviation; the
machine-readable analysis retains the corresponding summaries for every raw
AURC as well.
"""

from __future__ import annotations

import argparse
import math
import os
import tempfile
from pathlib import Path
from typing import Mapping

from scripts.analyze.main import CONTRASTS
from scripts.analyze.seed import validate_analysis_document
from selectseg.seed.extension import _load_json, _sha256


DATASETS = ("pet", "kvasir", "fives", "isic", "tn3k")
DATASET_LABELS = {
    "pet": "Oxford Pet",
    "kvasir": "Kvasir-SEG",
    "fives": "FIVES",
    "isic": "ISIC",
    "tn3k": "TN3K",
}
CONDITIONS = ("clipseg-target", "deeplabv3-target")
CONDITION_LABELS = {
    "clipseg-target": "CLIP-T",
    "deeplabv3-target": "DL-T",
}
CONTRAST_LABELS = {
    "dice_vs_nhd_under_dice": r"Dice $-$ HD (Dice risk)",
    "dice_vs_nhd_under_nhd": r"Dice $-$ HD (HD risk)",
    "nhd_vs_nhd95_under_nhd": r"HD $-$ HD95 (HD risk)",
    "nhd_vs_nhd95_under_nhd95": r"HD $-$ HD95 (HD95 risk)",
}
PLOT_CONTRAST_LABELS = {
    "dice_vs_nhd_under_dice": "Dice - HD | Dice risk",
    "dice_vs_nhd_under_nhd": "Dice - HD | HD risk",
    "nhd_vs_nhd95_under_nhd": "HD - HD95 | HD risk",
    "nhd_vs_nhd95_under_nhd95": "HD - HD95 | HD95 risk",
}


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    inputs = parser.add_mutually_exclusive_group(required=True)
    inputs.add_argument("--analysis")
    inputs.add_argument("--public-analysis")
    parser.add_argument("--expected-analysis-sha256")
    parser.add_argument("--output", required=True)
    parser.add_argument("--figure-output")
    return parser.parse_args(argv)


def load_analysis(path, *, expected_sha256):
    source = Path(path)
    if not source.is_file() or source.is_symlink():
        raise FileNotFoundError(
            f"seed analysis must be a regular non-symlink file: {source}"
        )
    observed = _sha256(source)
    if observed != expected_sha256:
        raise ValueError("seed analysis SHA-256 mismatch")
    analysis = _load_json(source)
    by_key = validate_analysis_document(analysis)
    return analysis, by_key, observed


def load_public_analysis(path, *, expected_sha256):
    """Load and validate a hash-pinned, path-free public seed analysis."""
    from scripts.maintenance.export_seed import _strict_loads, _validate_public_analysis

    source = Path(path)
    if not source.is_file() or source.is_symlink():
        raise FileNotFoundError(
            f"public seed analysis must be a regular non-symlink file: {source}"
        )
    observed = _sha256(source)
    if observed != expected_sha256:
        raise ValueError("public seed analysis SHA-256 mismatch")
    analysis = _validate_public_analysis(
        _strict_loads(source.read_bytes(), source=str(source))
    )
    by_key = {(cell["dataset"], cell["condition"]): cell for cell in analysis["cells"]}
    if len(by_key) != len(analysis["cells"]):
        raise ValueError("public seed analysis contains duplicate cells")
    return analysis, by_key, observed


def _cell(summary):
    values = summary["values"]
    return " / ".join(f"{100 * float(values[str(seed)]):+.2f}" for seed in (0, 1, 2))


def _dispersion_cell(summary):
    mean = 100 * float(summary["mean"])
    sample_sd = 100 * float(summary["sample_standard_deviation"])
    value_range = 100 * float(summary["range"])
    return rf"{mean:+.2f} $\pm$ {sample_sd:.2f} [{value_range:.2f}]"


def _write_text_new(path, payload):
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.link(temporary, destination)
        except FileExistsError as error:
            raise FileExistsError(f"refusing to overwrite {destination}") from error
    finally:
        temporary.unlink(missing_ok=True)


def render_table(analysis, by_key, *, analysis_sha256):
    gate = "fired" if analysis["gate_c"]["fired"] else "not fired"
    lines = [
        "% AUTO-GENERATED by scripts/render_binary_seed_extension.py; DO NOT EDIT.",
        f"% Source analysis.json SHA-256: {analysis_sha256}",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Target-model training-seed sensitivity. Panel (a) reports each signed "
        r"AURC contrast for seeds 0 / 1 / 2; panel (b) reports mean $\pm$ sample SD "
        r"[range]. All entries are multiplied by 100 for display only, and negative "
        r"values favor the left score. Seeds are checkpoint-level descriptive replicates "
        r"and are not pooled as images; the machine-readable source also retains the "
        rf"same summaries for every raw AURC. Gate C was {gate}.}}",
        r"\label{tab:seed-robustness}",
        r"\scriptsize",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"\multicolumn{7}{l}{\textit{(a) Seed-specific contrast: seed 0 / seed 1 / seed 2}} \\",
        "Model & Contrast & "
        + " & ".join(DATASET_LABELS[dataset] for dataset in DATASETS)
        + r" \\",
        r"\midrule",
    ]
    for condition_index, condition in enumerate(CONDITIONS):
        for contrast in CONTRASTS:
            cells = [
                _cell(
                    by_key[(dataset, condition)]["summary"]["contrasts"][contrast.name]
                )
                for dataset in DATASETS
            ]
            lines.append(
                " & ".join(
                    [
                        CONDITION_LABELS[condition],
                        CONTRAST_LABELS[contrast.name],
                        *cells,
                    ]
                )
                + r" \\"
            )
        if condition_index + 1 < len(CONDITIONS):
            lines.append(r"\midrule")
    lines.extend(
        [
            r"\midrule",
            r"\multicolumn{7}{l}{\textit{(b) Across-seed summary: mean $\pm$ sample SD [range]}} \\",
            r"\midrule",
        ]
    )
    for condition_index, condition in enumerate(CONDITIONS):
        for contrast in CONTRASTS:
            cells = [
                _dispersion_cell(
                    by_key[(dataset, condition)]["summary"]["contrasts"][contrast.name]
                )
                for dataset in DATASETS
            ]
            lines.append(
                " & ".join(
                    [
                        CONDITION_LABELS[condition],
                        CONTRAST_LABELS[contrast.name],
                        *cells,
                    ]
                )
                + r" \\"
            )
        if condition_index + 1 < len(CONDITIONS):
            lines.append(r"\midrule")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def macro_contrast_values(
    by_key: Mapping[tuple[str, str], dict], *, contrast_name: str
) -> list[float]:
    """Return the target-condition macro contrast for each training seed."""
    keys = [(dataset, condition) for dataset in DATASETS for condition in CONDITIONS]
    return [
        100
        * math.fsum(
            float(
                by_key[key]["summary"]["contrasts"][contrast_name]["values"][str(seed)]
            )
            for key in keys
        )
        / len(keys)
        for seed in (0, 1, 2)
    ]


def render_figure(
    by_key: Mapping[tuple[str, str], dict], output: str | os.PathLike[str]
) -> Path:
    """Render the four predeclared macro contrasts across training seeds."""
    import matplotlib.pyplot as plt

    destination = Path(output)
    if destination.exists() or destination.is_symlink():
        raise FileExistsError(f"refusing to overwrite seed figure: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)

    colors = ("#1769aa", "#d1495b", "#2a9d8f", "#7b2cbf")
    markers = ("o", "s", "^", "D")
    figure, axis = plt.subplots(figsize=(6.8, 3.8))
    axis.axhline(0, color="0.45", linewidth=1, linestyle="--")
    for (contrast_name, label), color, marker in zip(
        PLOT_CONTRAST_LABELS.items(), colors, markers, strict=True
    ):
        axis.plot(
            (0, 1, 2),
            macro_contrast_values(by_key, contrast_name=contrast_name),
            color=color,
            marker=marker,
            linewidth=1.7,
            markersize=5,
            label=label,
        )
    axis.set_xticks((0, 1, 2))
    axis.set_xlabel("Training seed")
    axis.set_ylabel(r"Macro AURC contrast $\times 100$")
    axis.set_title("Checkpoint sensitivity (10 target conditions)")
    axis.grid(axis="y", color="0.9", linewidth=0.7)
    axis.legend(frameon=False, fontsize=9, ncol=2, loc="best")
    figure.tight_layout()

    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.stem}.",
        suffix=destination.suffix,
        dir=destination.parent,
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        figure.savefig(temporary, bbox_inches="tight", metadata={"Creator": __name__})
        os.link(temporary, destination)
    finally:
        plt.close(figure)
        temporary.unlink(missing_ok=True)
    return destination


def main(argv=None):
    args = parse_args(argv)
    if args.public_analysis:
        if args.expected_analysis_sha256 is None:
            raise ValueError("--public-analysis requires --expected-analysis-sha256")
        analysis, by_key, digest = load_public_analysis(
            args.public_analysis, expected_sha256=args.expected_analysis_sha256
        )
    else:
        if args.expected_analysis_sha256 is None:
            raise ValueError("--analysis requires --expected-analysis-sha256")
        analysis, by_key, digest = load_analysis(
            args.analysis, expected_sha256=args.expected_analysis_sha256
        )
    output = Path(args.output)
    payload = render_table(analysis, by_key, analysis_sha256=digest)
    _write_text_new(output, payload)
    print(f"saved {output}")
    print(f"table_sha256={_sha256(output)}")
    if args.figure_output:
        figure = render_figure(by_key, args.figure_output)
        print(f"saved {figure}")
    return output


if __name__ == "__main__":
    main()
