"""Render the locked three-seed robustness summary as a compact LaTeX table.

The analysis stores raw AURC units.  Consistent with the manuscript, this
renderer displays signed AURC contrasts multiplied by 100 and leaves all
underlying JSON values unchanged.  It reports both the three checkpoint-level
values and their predeclared mean, range, and sample standard deviation; the
machine-readable analysis retains the corresponding summaries for every raw
AURC as well.
"""

from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path

from scripts.analyze_binary import CONTRASTS
from scripts.analyze_binary_seed_extension import validate_analysis_document
from selectseg.binary_seed_extension import _load_json, _sha256


DATASETS = ("pet", "kvasir", "fives", "isic", "tn3k")
DATASET_LABELS = {
    "pet": "Oxford Pet",
    "kvasir": "Kvasir-SEG",
    "fives": "FIVES",
    "isic": "ISIC",
    "tn3k": "TN3K",
}
CONDITIONS = ("clipseg-target", "deeplabv3-target")
CONDITION_LABELS = {
    "clipseg-target": "CLIP-T",
    "deeplabv3-target": "DL-T",
}
CONTRAST_LABELS = {
    "dice_vs_nhd_under_dice": r"Dice $-$ nHD (Dice risk)",
    "dice_vs_nhd_under_nhd": r"Dice $-$ nHD (nHD risk)",
    "nhd_vs_nhd95_under_nhd": r"nHD $-$ nHD95 (nHD risk)",
    "nhd_vs_nhd95_under_nhd95": r"nHD $-$ nHD95 (nHD95 risk)",
}


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--analysis", required=True)
    parser.add_argument("--expected-analysis-sha256", required=True)
    parser.add_argument("--output", required=True)
    return parser.parse_args(argv)


def load_analysis(path, *, expected_sha256):
    source = Path(path)
    if not source.is_file() or source.is_symlink():
        raise FileNotFoundError(
            f"seed analysis must be a regular non-symlink file: {source}"
        )
    observed = _sha256(source)
    if observed != expected_sha256:
        raise ValueError("seed analysis SHA-256 mismatch")
    analysis = _load_json(source)
    by_key = validate_analysis_document(analysis)
    return analysis, by_key, observed


def _cell(summary):
    values = summary["values"]
    return " / ".join(f"{100 * float(values[str(seed)]):+.2f}" for seed in (0, 1, 2))


def _dispersion_cell(summary):
    mean = 100 * float(summary["mean"])
    sample_sd = 100 * float(summary["sample_standard_deviation"])
    value_range = 100 * float(summary["range"])
    return rf"{mean:+.2f} $\pm$ {sample_sd:.2f} [{value_range:.2f}]"


def _write_text_new(path, payload):
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.link(temporary, destination)
        except FileExistsError as error:
            raise FileExistsError(f"refusing to overwrite {destination}") from error
    finally:
        temporary.unlink(missing_ok=True)


def render_table(analysis, by_key, *, analysis_sha256):
    gate = "fired" if analysis["gate_c"]["fired"] else "not fired"
    lines = [
        "% AUTO-GENERATED by scripts/render_binary_seed_extension.py; DO NOT EDIT.",
        f"% Source analysis.json SHA-256: {analysis_sha256}",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Target-model training-seed sensitivity. Panel (a) reports each signed "
        r"AURC contrast for seeds 0 / 1 / 2; panel (b) reports mean $\pm$ sample SD "
        r"[range]. All entries are multiplied by 100 for display only, and negative "
        r"values favor the left score. Seeds are checkpoint-level descriptive replicates "
        r"and are not pooled as images; the machine-readable source also retains the "
        rf"same summaries for every raw AURC. Gate C was {gate}.}}",
        r"\label{tab:seed-robustness}",
        r"\scriptsize",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"\multicolumn{7}{l}{\textit{(a) Seed-specific contrast: seed 0 / seed 1 / seed 2}} \\",
        "Model & Contrast & "
        + " & ".join(DATASET_LABELS[dataset] for dataset in DATASETS)
        + r" \\",
        r"\midrule",
    ]
    for condition_index, condition in enumerate(CONDITIONS):
        for contrast in CONTRASTS:
            cells = [
                _cell(
                    by_key[(dataset, condition)]["summary"]["contrasts"][contrast.name]
                )
                for dataset in DATASETS
            ]
            lines.append(
                " & ".join(
                    [
                        CONDITION_LABELS[condition],
                        CONTRAST_LABELS[contrast.name],
                        *cells,
                    ]
                )
                + r" \\"
            )
        if condition_index + 1 < len(CONDITIONS):
            lines.append(r"\midrule")
    lines.extend(
        [
            r"\midrule",
            r"\multicolumn{7}{l}{\textit{(b) Across-seed summary: mean $\pm$ sample SD [range]}} \\",
            r"\midrule",
        ]
    )
    for condition_index, condition in enumerate(CONDITIONS):
        for contrast in CONTRASTS:
            cells = [
                _dispersion_cell(
                    by_key[(dataset, condition)]["summary"]["contrasts"][contrast.name]
                )
                for dataset in DATASETS
            ]
            lines.append(
                " & ".join(
                    [
                        CONDITION_LABELS[condition],
                        CONTRAST_LABELS[contrast.name],
                        *cells,
                    ]
                )
                + r" \\"
            )
        if condition_index + 1 < len(CONDITIONS):
            lines.append(r"\midrule")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv=None):
    args = parse_args(argv)
    analysis, by_key, digest = load_analysis(
        args.analysis, expected_sha256=args.expected_analysis_sha256
    )
    output = Path(args.output)
    payload = render_table(analysis, by_key, analysis_sha256=digest)
    _write_text_new(output, payload)
    print(f"saved {output}")
    print(f"table_sha256={_sha256(output)}")
    return output


if __name__ == "__main__":
    main()
